extends RefCounted

## ============================================================================
## WEAPONS - which gun model you hold for each power.
## ============================================================================
##
## Rocklyn's scripts/power_abilities.gd decides what every power DOES (damage,
## fire rate, rockets, speed...). This file only decides what the gun in your
## hands LOOKS like while you carry that power, so a player can tell from
## across the room that someone has picked up the 2 Shot or a rocket launcher.
##
##     const Weapons = preload("res://scripts/weapons.gd")
##     var look: Dictionary = Weapons.for_power("two_shot")
##     PaintKit.instance(look.model)        # first person
##     PaintKit.instance(look.model + "_prop")   # what other players see
##
## The models are generated by tools/blender/create_weapon_*.py (and
## create_paint_blaster.py) into models/generated/. Every one has a `Muzzle`
## part where shots leave it, a `Fill` part showing the paint left, and the
## gun-skin material roles, so the menu's gun skin restyles all of them.
##
##   model        models/generated/<model>.glb, plus <model>_prop.glb
##   name         shown in the HUD next to the paint tank
##   view_offset  nudges the first-person model so it sits well on screen

## No power (and powers that do not change the gun: Invisibility, Speed).
const DEFAULT := {"model": "paint_blaster", "name": "PAINT BLASTER", "view_offset": Vector3.ZERO}

const BY_POWER := {
	# 2 Shot: two hits paint anyone out - a long ink pen of a sniper.
	"two_shot": {"model": "weapon_fine_liner", "name": "FINE LINER", "view_offset": Vector3(-0.02, 0.0, -0.12)},
	# Rocket Launcher: a drum launcher with a big paint blob in its mouth.
	"rocket_launcher": {"model": "weapon_blob_lobber", "name": "BLOB LOBBER", "view_offset": Vector3.ZERO},
	# Sprayer: 2.5x the fire rate - the glowing prism gun.
	"sprayer": {"model": "weapon_prism_beam", "name": "PRISM BEAM", "view_offset": Vector3.ZERO},
}

## Built and ready for a future power, but no power uses it yet.
const UNUSED_MODELS := ["weapon_splat_bucket"]


## The look for a power id ("" = no power).
static func for_power(power_id: String) -> Dictionary:
	return BY_POWER.get(power_id, DEFAULT)


## Every gun model the game can show, for scripts/visual/shader_warmup.gd.
static func all_models() -> Array[String]:
	var models: Array[String] = [str(DEFAULT.model)]
	for look in BY_POWER.values():
		models.append(str(look.model))
	return models
